name: sdb_app
description: "SDB - Digital Banking App"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.4.0
  shared_preferences: ^2.5.0
  flutter_secure_storage: ^9.2.3
  intl: ^0.20.0
  fl_chart: ^0.70.2
  shimmer: ^3.0.0
  cached_network_image: ^3.4.1
  google_fonts: ^6.2.1
  flutter_svg: ^2.0.16
  pin_code_fields: ^8.0.1
  local_auth: ^2.3.0
  animate_do: ^3.3.4
  firebase_core: ^4.4.0
  firebase_auth: ^6.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
